### ISSUE TITLE
pipeline-creation

### ISSUE THREAD

**Issue by snowmang1** [snowmang1/sxeme#10]
## Tasks
- [ ] Rust compilation (build & test only)
    - [ ] cargo build should complete without error (warnings are fine for non-trunk branch)
    - [ ] cargo test should strictly block when tests do not pass
    - if possible generate coverage and post
- [ ] Readme
    - [ ] list status of test & build
    - [ ] Rustc version
    - cargo version ?
    - list license
    - [ ] update to list build and testing steps (includes install of cargo-llvm-cov)
