### ISSUE TITLE
Write Scanner mk1

### ISSUE THREAD

**Issue by snowmang1** [snowmang1/sxeme#3]
### Tasks
- [x] Write Scanner for all text input
- [x] Ignore Comments
    - [x] single line
    - [x] block
- [x] Scanner should be unit testable
- [x] Callable from Parser

### Notes
- Speed is not an issue with the mk1 series
- Scanner will not directly create the Read stream, only use it
- Scanner errors include: input stream err
