### ISSUE TITLE
Parser: math

### ISSUE THREAD

**Issue by snowmang1** [snowmang1/sxeme#4]
### Tasks
- [x] Paser start
    - [x] Open input stream and call scanner
    - [x] implement handle identification
    - [x] use stack to store inter-reduce data
- [x] Paser for math ops only
	- [x] _+_
	- [x] _-_
	- [x] _/_
	- [x] _*_
	- [ ] _modulo_
	- [ ] _ceiling_
	- [ ] _abs_
	- [ ] _denominator_
	- [ ] _square_
	- [ ] _quotient_
	- [ ] _gcd_
	- [ ] _expt_
	- [ ] _lcm_
- [x] Testing
    - [x] coverage of all operator functions
    - [x] coverage of error library
    - [x] coverage of token object (hierarchy of objects)
- [x] Bottom-up Parse Table needed for Report
    - Idealy with accompanying NFA
        - [x] StarUML / Latex table + Latex Diagram

### Notes
- This badly needs a testing pipeline else I am going to taint trunk
- _LR(1)_ Bottom up Parsering is the goal
- No Rollback in the parse
- the only type signiture for parser mk1 is integer
