### ISSUE TITLE
llvm Vars

### ISSUE THREAD

**Issue by snowmang1** [snowmang1/sxeme#8]
## Tasks
- [x] #4 
- [ ] #5 
- [ ] integrate variable names into IR
- [ ] IR should use SSA form
- [ ] variables should be shadowed & NEVER mutable
- [ ] vars should obey scope
## Notes
