### ISSUE TITLE
Parser: const glob

### ISSUE THREAD

**Issue by snowmang1** [snowmang1/sxeme#9]
## Notes
- scanner should grab constants as globs delimited by whitespace
- scanner should read lexemes efficiently, delimiting them by white space
    - this means that the parser will get mangled lexemes s.a "(+"
    - the parser should be able to detect this and smart enough to dissect it
- possible solve for mangled lexemes
    - spawn thread/process to dissect lexeme inside scanner

### Tasks
- [ ] scanner delimits by whitespace
- [ ] parser dissects mangled lexemes
- [ ] scanner spawns native thread for dissecting lexemes
